import { useEffect, useState, type FormEvent } from 'react';
import { Modal } from '../../../../shared/ui/Modal/Modal';
import { DatePicker } from '../../../../shared/ui/DatePicker/DatePicker';
import type { Classe } from '../../../classes/types/classe.types';
import type { Matiere } from '../../../matieres/types/matiere.types';
import type { MatiereClasseConfig } from '../../types/config.types';

interface Props { open: boolean; mode: 'create' | 'edit'; item: MatiereClasseConfig | null; classes: Classe[]; matieres: Matiere[]; loading: boolean; onClose: () => void; onSave: (data: MatiereClasseConfig) => Promise<void>; onDelete: (id: number) => void; }
export function ConfigForm({ open, mode, item, classes, matieres, loading, onClose, onSave, onDelete }: Props) {
  const [classeId, setClasseId] = useState<number | ''>(''); const [matiereId, setMatiereId] = useState<number | ''>(''); const [dateDebut, setDateDebut] = useState(''); const [dateFin, setDateFin] = useState(''); const [volume, setVolume] = useState<number | ''>('');
  useEffect(() => { setClasseId(item?.classeId ?? ''); setMatiereId(item?.matiereId ?? ''); setDateDebut(item?.dateDebut ?? ''); setDateFin(item?.dateFin ?? ''); setVolume(item?.volumeHorairePeriode ?? ''); }, [item, open]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void onSave({ id: item?.id, classeId: classeId === '' ? undefined : classeId, matiereId: matiereId === '' ? undefined : matiereId, dateDebut: dateDebut || null, dateFin: dateFin || null, volumeHorairePeriode: volume === '' ? null : volume }); };
  return <Modal open={open} title={mode === 'create' ? 'Ajouter une configuration' : 'Modifier la configuration'} description="Définissez le volume horaire attendu pour une matière et une classe." onClose={onClose} onSubmit={submit} loading={loading} dangerAction={mode === 'edit' && item?.id ? { label: 'Supprimer', onClick: () => onDelete(item.id!) } : undefined}><div className="form-grid"><div className="form-field"><label>Classe</label><select value={classeId} onChange={(e) => setClasseId(e.target.value ? Number(e.target.value) : '')} required><option value="">Sélectionner…</option>{classes.map((classe) => <option key={classe.id} value={classe.id}>{classe.nom}</option>)}</select></div><div className="form-field"><label>Matière</label><select value={matiereId} onChange={(e) => setMatiereId(e.target.value ? Number(e.target.value) : '')} required><option value="">Sélectionner…</option>{matieres.map((matiere) => <option key={matiere.id} value={matiere.id}>{matiere.nom}</option>)}</select></div><div className="form-field"><label>Date de début</label><DatePicker value={dateDebut} onChange={setDateDebut} placeholder="Date de début" /></div><div className="form-field"><label>Date de fin</label><DatePicker value={dateFin} onChange={setDateFin} placeholder="Date de fin" /></div><div className="form-field form-field--full"><label>Volume horaire de la période</label><input type="number" min="0" value={volume} onChange={(e) => setVolume(e.target.value === '' ? '' : Number(e.target.value))} placeholder="Ex. 120" /></div></div></Modal>;
}
