import { useEffect, useState, type FormEvent } from 'react';
import { Modal } from '../../../../shared/ui/Modal/Modal';
import type { Matiere } from '../../../matieres/types/matiere.types';
import type { Professeur, ProfesseurDayOff } from '../../types/professeur.types';
import './ProfesseurForm.css';

interface Props { open: boolean; mode: 'create' | 'edit'; item: Professeur | null; matieres: Matiere[]; loading: boolean; onClose: () => void; onSave: (data: Professeur) => Promise<void>; onDelete: (id: number) => void; }
const days = [{ value: 1, label: 'Lundi' }, { value: 2, label: 'Mardi' }, { value: 3, label: 'Mercredi' }, { value: 4, label: 'Jeudi' }, { value: 5, label: 'Vendredi' }];

export function ProfesseurForm({ open, mode, item, matieres, loading, onClose, onSave, onDelete }: Props) {
  const [nom, setNom] = useState(''); const [prenom, setPrenom] = useState(''); const [email, setEmail] = useState(''); const [heures, setHeures] = useState(0);
  const [maxJour, setMaxJour] = useState<number | ''>(''); const [maxSemaine, setMaxSemaine] = useState<number | ''>(''); const [maxSeance, setMaxSeance] = useState<number | ''>(''); const [plage, setPlage] = useState(''); const [matiereIds, setMatiereIds] = useState<number[]>([]); const [daysOff, setDaysOff] = useState<ProfesseurDayOff[]>([]);
  useEffect(() => {
    setNom(item?.nom ?? ''); setPrenom(item?.prenom ?? ''); setEmail(item?.email ?? ''); setHeures(item?.nb_heures ?? 0); setMaxJour(item?.maxHeuresParJour ?? ''); setMaxSemaine(item?.maxHeuresParSemaine ?? ''); setMaxSeance(item?.maxHeuresParSeance ?? ''); setPlage(item?.plageHorairePreferee?.libelle ?? ''); setMatiereIds(item?.matieres?.flatMap((matiere) => matiere.id ? [matiere.id] : []) ?? []); setDaysOff(item?.daysOff ? [...item.daysOff] : []);
  }, [item, open]);
  const toggleMatiere = (id: number) => setMatiereIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const toggleDay = (jourSemaine: number) => setDaysOff((current) => current.some((day) => day.jourSemaine === jourSemaine) ? current.filter((day) => day.jourSemaine !== jourSemaine) : [...current, { jourSemaine }]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void onSave({ id: item?.id, nom: nom.trim(), prenom: prenom.trim(), email: email.trim(), nb_heures: heures, maxHeuresParJour: maxJour === '' ? undefined : maxJour, maxHeuresParSemaine: maxSemaine === '' ? undefined : maxSemaine, maxHeuresParSeance: maxSeance === '' ? undefined : maxSeance, plageHorairePreferee: plage.trim() ? { libelle: plage.trim() } : null, matieres: matieres.filter((matiere) => matiere.id && matiereIds.includes(matiere.id)), daysOff, seances: item?.seances ?? [] }); };
  return <Modal open={open} size="lg" title={mode === 'create' ? 'Ajouter un professeur' : 'Modifier le professeur'} description="Identité, charge d'enseignement et contraintes utilisées par le moteur de planning." onClose={onClose} onSubmit={submit} loading={loading} dangerAction={mode === 'edit' && item?.id ? { label: 'Supprimer', onClick: () => onDelete(item.id!) } : undefined}><div className="form-grid"><div className="form-field"><label>Nom</label><input value={nom} onChange={(e) => setNom(e.target.value)} required /></div><div className="form-field"><label>Prénom</label><input value={prenom} onChange={(e) => setPrenom(e.target.value)} required /></div><div className="form-field form-field--full"><label>Email</label><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="form-field"><label>Volume horaire total</label><input type="number" min="0" value={heures} onChange={(e) => setHeures(Number(e.target.value))} /></div><div className="form-field"><label>Plage horaire préférée</label><input value={plage} onChange={(e) => setPlage(e.target.value)} placeholder="Ex. Matin" /></div><section className="form-section professeur-form__constraints"><p className="form-section__title">Contraintes horaires</p><div className="professeur-form__constraint-grid"><div className="form-field"><label>Max / jour</label><input type="number" min="0" value={maxJour} onChange={(e) => setMaxJour(e.target.value === '' ? '' : Number(e.target.value))} /></div><div className="form-field"><label>Max / semaine</label><input type="number" min="0" value={maxSemaine} onChange={(e) => setMaxSemaine(e.target.value === '' ? '' : Number(e.target.value))} /></div><div className="form-field"><label>Max / séance</label><input type="number" min="0" value={maxSeance} onChange={(e) => setMaxSeance(e.target.value === '' ? '' : Number(e.target.value))} /></div></div></section><section className="form-section"><p className="form-section__title">Matières enseignées</p><div className="form-chip-grid">{matieres.map((matiere) => matiere.id ? <button key={matiere.id} type="button" className={`form-chip${matiereIds.includes(matiere.id) ? ' is-selected' : ''}`} onClick={() => toggleMatiere(matiere.id!)}>{matiere.nom}</button> : null)}</div></section><section className="form-section"><p className="form-section__title">Jours indisponibles</p><div className="form-chip-grid">{days.map((day) => <button key={day.value} type="button" className={`form-chip${daysOff.some((value) => value.jourSemaine === day.value) ? ' is-selected' : ''}`} onClick={() => toggleDay(day.value)}>{day.label}</button>)}</div></section></div></Modal>;
}
